apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx:alpine
    command: ['sh', '-c', 'test -f /mnt/data/test.txt & sleep 3600']
    volumeMounts:
    - mountPath: /data
      name: mydir
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'touch /mnt/data/test.txt & sleep 60']
    volumeMounts:
    - mountPath: /mnt/data
      name: mydir
  volumes:
  - name: mydir
    hostPath:
      # Ensure the file directory is created.
      path: /mnt/data
      type: DirectoryOrCreate

