apiVersion: v1
kind: Pod
metadata:
  name: init-test-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx:alpine
    command: ['sh', '-c', 'if [ -f /data/shared-file.txt ]; then rm -rf /data/shared-file.txt; touch /data/test.txt; sleep 99999; else exit; fi']
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'mkdir /data; echo "bye"> /data/shared-file.txt']
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
