apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-test
  name: busybox-test
spec:
  containers:
  - command: ["sh","-c", "sleep 3600"]
    image: busybox
    name: busybox-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
