apiVersion: v1
kind: Pod
metadata:
  name: secret-from-env
spec:
  containers:
    - name: envars-test-container
      image: nginx
      env:
      - name: username
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: username
      - name: password
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: password
