apiVersion: v1
kind: Pod
metadata:
  labels:
    run: specific-pod
  name: specific-pod
spec:
  containers:
  - args:
    - nginx
    image: nginx:alpine
    name: specific-pod
    resources: {}
  restartPolicy: Always
  nodeName: worker-2
